### ISSUE TITLE
Undefined constant "Laravel\Reverb\Servers\Reverb\Console\Commands\SIGINT"

### ISSUE THREAD

**Issue by jbarreraballestas** [laravel/reverb#74] opened 2024-03-13 14:08 UTC
### Reverb Version

v1.0.0-beta2

### Laravel Version

10.48.2

### PHP Version

8.2.12

### Description

Running reverb on laravel 10 on windows 10

### Steps To Reproduce

New laravel 10 app
```bash
composer create-project --prefer-dist laravel/laravel laravel10-reverb "10.*"
```

```bash
cd laravel10-reverb
```
Add reverb
```bash
composer require laravel/reverb:@beta
```
Install reverb (in this step console still waiting, need to press enter or something)
```bash
php artisan reverb:install
``` 
Start reverb
```bash
php artisan reverb:start
```
![image](https://github.com/laravel/reverb/assets/52984437/3a438de6-8ae1-472a-966d-4686e9954c85)

**Comment by driesvints** [comment] 2024-03-13 14:42
Duplicate of https://github.com/laravel/reverb/issues/65

**Closed by driesvints** 2024-03-13 14:42 UTC
