### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by romsVLM** [laravel/reverb#71] opened 2024-03-13 10:11 UTC
### Reverb Version

beta

### Laravel Version

10.48

### PHP Version

8.2

### Description

Hello, unable to run the "**php artisan reverb:start**" command on Windows.

Here is the error:
**In StartServer.php line 150:**

**Undefined constant "Laravel\Reverb\Servers\Reverb\Console\Commands\SIGINT"**

It appears that Reverb uses the **PCNTL** PHP extension which is not available on Windows.

There was the same problem on Laravel 11 and a fix was made.

Would it also be possible to have a fix for Windows?

Thanks in advance

### Steps To Reproduce

Install Laravel Reverb on windows on Laravel 10.48 then run **php artisan reverb:start**

**Comment by driesvints** [comment] 2024-03-13 10:12
Duplicate of https://github.com/laravel/reverb/issues/65

**Closed as completed by driesvints** 2024-03-13 10:12 UTC

**Comment by romsVLM** [comment] 2024-03-13 10:16
> Duplicate of #65

Not the same issue. I am on Laravel 10.X not 11
