### ISSUE TITLE
wss connection failure for secure local site

### ISSUE THREAD

**Issue by paul-adams-985** [laravel/reverb#153] opened 2024-04-16 14:07 UTC
### Reverb Version

1.0.0-beta6

### Laravel Version

11.3.1

### PHP Version

8.3

### Description

I have a Laravel 11 project. Servers are managed locally with Herd. I have secured my site.
Everything works beautifully except Reverb - which is wonderful, btw!

```
 WebSocket connection to 'wss://my-site.test/app/xjdam3dnj7kmzzviunel?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: echo.js:6
```

in my .env

```
PUSHER_APP_ID=xxxx
PUSHER_APP_KEY=xxxxx
PUSHER_APP_SECRET=xxxx
PUSHER_HOST=
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=eu

VITE_APP_NAME="${APP_NAME}"
VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="${PUSHER_HOST}"
VITE_PUSHER_PORT="${PUSHER_PORT}"
VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

REVERB_APP_ID=179981
REVERB_APP_KEY=xjdam3dnj7kmzzviunel
REVERB_APP_SECRET=hzeak0dakwzq5fdvn5sp
REVERB_HOST="my-site.test"
REVERB_PORT=443
REVERB_SCHEME=https

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```

Any pointers and help would be much appreciated.

Paul :)

### Steps To Reproduce

1) Secure site in Herd
2) Restart Reverb server
3) Review browser errors.

![image](https://github.com/laravel/reverb/assets/8458394/1e276e4f-3ea9-4a6d-9f5c-3f6d35d73799)

**Comment by paul-adams-985** [comment] 2024-04-16 14:45
Could you give me more  direction on what info would best help?
Huge, enormous thanks :)

**Comment by vdev-chris** [comment] 2024-04-16 14:46
I am having the same issue. It's a brand new laravel 11 project. Installed broadcasting with reverb. It looks like the issue is related to the https connection. All of the guides I am finding are people using unsecure connections. Our local setup through herd secures the connection. 

Any insight would be helpful. 

Env looks like: 

`REVERB_APP_ID=local-app-id
REVERB_APP_KEY=local-app-key
REVERB_APP_SECRET=local-app-secret
REVERB_HOST="local-site-name.test"
REVERB_PORT=8080
REVERB_SCHEME=https

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"`

The error on page load is: 

"WebSocket connection to 'wss://local-site-name.test:8080/app/a6l43rqquqjiesdgphb7?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: "

**Comment by driesvints** [comment] 2024-04-16 14:53
@paul-adams-985 just labeling this that this needs more info from Joe before proceeding.

**Comment by vdev-chris** [comment] 2024-04-16 15:23
@joedixon I was using Chrome. 

Out of curiosity, I tried Firefox before following your instructions and Firefox was actually working fine. 

I then followed your instructions and it began working. 

Is this something that would need to happen every session? 

Chrome is up to date, just as a further FYI.

**Comment by paul-adams-985** [comment] 2024-04-16 17:38
Hello! Appologies for the delayed response. 

It did not work for me.  However, I do not get a regular 404, I get a "Not found." message.

I tried both Chrome and Firefox with my nginx modifications and them again with it returned to the original setup.

Here is the message on firefox.

![image](https://github.com/laravel/reverb/assets/8458394/e6f9ad9a-7348-45ef-92a7-fe77bc2fa3f2)


![image](https://github.com/laravel/reverb/assets/8458394/b4207f3a-25d6-40ce-b190-1c1d7f89c489)

**Comment by vdev-chris** [comment] 2024-04-16 17:46
> Hello! Appologies for the delayed response.
> 
> It did not work for me. However, I do not get a regular 404, I get a "Not found." message.
> 
> I tried both Chrome and Firefox with my nginx modifications and then again with nginx returned to the original setup.
> 
> Here is the message on firefox.
> 
> ![image](https://private-user-images.githubusercontent.com/8458394/322945062-e6f9ad9a-7348-45ef-92a7-fe77bc2fa3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODk4MDIsIm5iZiI6MTcxMzI4OTUwMiwicGF0aCI6Ii84NDU4Mzk0LzMyMjk0NTA2Mi1lNmY5YWQ5YS03MzQ4LTQ1ZWYtOTJhNy1mZTc3YmMyZmEzZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTZUMTc0NTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDZlMTEwYTg2NGI4YWExNzM0YWJmNDNjNDNmNzI2YjgzMDgxN2Q3Y2Y0YzYyZTA3NjYxMGUwMzg1ZTQyNTJkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rNdjZw2qCd9uf7cmZ1D7-I9PThX0XxXTWqfQy1g4WzY)
> 
> ![image](https://private-user-images.githubusercontent.com/8458394/322944474-b4207f3a-25d6-40ce-b190-1c1d7f89c489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODk4MDIsIm5iZiI6MTcxMzI4OTUwMiwicGF0aCI6Ii84NDU4Mzk0LzMyMjk0NDQ3NC1iNDIwN2YzYS0yNWQ2LTQwY2UtYjE5MC0xYzFkN2Y4OWM0ODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTZUMTc0NTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQxMTQ5M2FkYzlmMWJlNDQxMDE1MDMwOTdjYTQ4ZjM3Mzg3MDkyZTRkZTUyZjk3YTQwYzVjOGZlYzQzMjkzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1CCDrMod61fXUfe91p6J1BqlqJ5Qw2sNMVNFkhTQnQU)

That's the intended response, I believe. After you've loaded this page, you should be able to close it and refresh the page that is connecting to your local site. It immediately update for me. 

To be clear, I had vite server up and running (through npm run dev). If you don't, you may need to rebuild?

**Comment by vdev-chris** [comment] 2024-04-16 17:47
Also, the port should still be 8080.

**Comment by paul-adams-985** [comment] 2024-04-16 17:50
OMG. I noticed a differnce between the port setting on your config and mine. I had previously tried with your setup.
But this time, after the http://site.test:8080 trick, it worked!!!

I now have another bug to work through. Most likely my bad coding and nothing to do with Reverb.

Thanks guys. Keep up the good work...

P.S. Is it worth putting something in the docs?

**Comment by vdev-chris** [comment] 2024-04-16 17:57
Still bizarre that the out-of-the-box install has issues with browser certificate recognition.

**Comment by paul-adams-985** [comment] 2024-04-16 18:03
Indeed. I have posted a solution on the Laracasts Forum.

**Comment by paul-adams-985** [comment] 2024-04-16 19:13
@joedixon and @driesvints Super-huge thanks for your fast responses and help. 
We're all very appreciative of all that you do. If you would like me to submit a PR for a note in the documentation, let me know.

**Comment by joedixon** [comment] 2024-04-16 20:14
> Still bizarre that the out-of-the-box install has issues with browser certificate recognition.

I agree, but unfortunately, it's not that straightforward 🥴

Reverb uses the certificates provided by Valet or Herd. As I understand it, they add a trusted certificate authority to the keychain and use that to sign the ceritificate for the site. So, the certificates should be trusted and they are in Firefox and Safari. For some reason, Chrome doesn't trust them until the host has been accessed over HTTPS first.

I'll keep looking into it and see if anything can be done.

**Comment by vdev-chris** [comment] 2024-04-16 20:29
Appreciate it. It's quite ironic to me that Chrome would be the oddball in this case. Considering that both Safari and Firefox are known for tighter security lol

**Comment by paul-adams-985** [comment] 2024-04-16 21:22
Quite. It's Chrome who needs to sort their game out on this one.

**Closed** 2024-04-17 21:19 UTC
Labels: needs more info

**Comment by bulgar989** [comment] 2024-08-09 09:13
Так в итоге как решить проблему, на https невозможно использовать ws

**Comment by braedencrankd** [comment] 2024-09-26 20:09
@kevinrrm Did you find a solution on Cloudways? I have a test server there and can't seem to get Reverb working. Thanks.

**Comment by BeHumanX** [comment] 2024-10-01 08:22
anyone have solution for ngrok? im trying to expose it to internet but seems like everytime wss:// request happen it suddenly close, i've tried to set the forceTLS to be false but its still won't work
