### ISSUE TITLE
local & reverse proxied /app path returns 404

### ISSUE THREAD

**Issue by Hue-OwO** [laravel/reverb#115] opened 2024-03-23 15:14 UTC
### Reverb Version

1.0

### Laravel Version

11.0

### PHP Version

8.2.7

### Description

idk if this is a bug or something wrong with the config, but reverb returns 404 when trying to connect locally or through caddy, i haven’t tried reverse proxying it through Nginx, guessing it wouldn’t of worked either because it returned 404 locally

reverb.php
![IMG_8881](https://github.com/laravel/reverb/assets/71944049/34614bdc-5c27-4c50-a676-e456377db730)
caddy
![IMG_8884](https://github.com/laravel/reverb/assets/71944049/1e59516b-4552-4f70-acd9-7381366ea131)
.env
![IMG_8886](https://github.com/laravel/reverb/assets/71944049/ddf9a319-004a-43bf-864c-607a59a8bc92)
![IMG_8885](https://github.com/laravel/reverb/assets/71944049/82b55d95-9b9e-4443-a4a9-4eca5bd9dab5)
firefox
![IMG_8890](https://github.com/laravel/reverb/assets/71944049/a20c9ff8-c7dc-4b56-84e4-d4a04678e592)
postman
![IMG_8889](https://github.com/laravel/reverb/assets/71944049/6645be3f-ecfd-4863-b962-c8e08db0f61c)

### Steps To Reproduce

connecting returns 404

**Comment by iqbalhasandev** [comment] 2024-03-24 04:56
I have faced the same problem. You can see I have given the solution here and if you face any problem you can comment there

https://github.com/laravel/reverb/issues/107#issuecomment-2016692366

**Comment by driesvints** [comment] 2024-03-25 15:34
Seems to be a duplicate of https://github.com/laravel/reverb/issues/107

**Closed by driesvints** 2024-03-25 15:34 UTC
